"""
Each new term in the Fibonacci sequence is generated by adding
the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.

https://projecteuler.net/problem=2
"""


def sum_even_fib_below(n: int) -> int:
    """ Sum of all even fibonacci numbers below 'n'."""
    total = 0
    a, b = 1, 2            # First 2 numbers of the fibonacci series
    while b < n:
        if b % 2 == 0:
            total += b
        a, b = b, a + b    # Continue the fibonacci sequence
    return total


if __name__ == '__main__':
    print(sum_even_fib_below(4000000))
